### ISSUE TITLE
Count of instances for full-synthetic transitivity inference dataset

### ISSUE THREAD

**Issue by PhMeier** [verypluming/transitivity#2]
Hello,
thanks for your work and providing the code!

I generated the full-synthetic transitivity inference dataset and a question came up:

In the paper in section "Boolean inference" is stated that you generate 3000 Boolean inference examples, 6000 veridical inference examples and 6000 composite inference examples.

I've exectued run_veridical.sh with a pruning rate of 100. This produced results_veridical/train.tsv (4242 instances) and dev_matched.tsv (2121 instances). Regarding the paper, I expected around 12000 to 15000 instances. Maybe I'm doing a mistake or I am missing out something regarding the number of examples, but from my understanding, the pruning parameter needs to be increased in order to generate more instances.

Therefore I wanted to ask which pruning parameter was used to generate the results like in the paper.

**Comment by verypluming** [comment]
Hi, I answered your question from your email and here close this issue. Thanks for your comment!

**Comment by PhMeier** [comment]
Hello,
thank you very much for your fast answer! However, I think you confused me with somebody else, since I did not write an email.

**Comment by verypluming** [comment]
Sorry! I confused someone else who asked the question related to yours. Regarding your question, we are sorry for forgetting the exact pruning parameter. Please change pruning_rate and sample the generated data according to the statistics we mentioned in our paper.
